### ISSUE TITLE
Problems with scripts

### ISSUE THREAD

**Issue by zakharfsk** [zakharfsk/auto-reporting-fake-channels#3]
Якщо у вас виникають якісь проблеми з використанням скріпта, пишіть сюда

**Comment by marko-yaciv** [comment]
Варто було б ще хендлити екзепшини для неправильного паролю(коли двухфакторна авторизація і в інших місцях), бо програма просто падає))

**Comment by zakharfsk** [comment]
@marko-yaciv окей зрозумів завтра випущу патч)

**Comment by alexandrzhulev** [comment]
```
Unhandled exception on check
Traceback (most recent call last):
  File "/home/oleksandr/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "main.py", line 101, in check
    channel_info_by_url = await client.get_entity(url)
  File "/home/oleksandr/.local/lib/python3.8/site-packages/telethon/client/users.py", line 335, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "/home/oleksandr/.local/lib/python3.8/site-packages/telethon/client/users.py", line 553, in _get_entity_from_string
    result = await self(
  File "/home/oleksandr/.local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/oleksandr/.local/lib/python3.8/site-packages/telethon/client/users.py", line 52, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 2941 seconds is required (caused by ResolveUsernameRequest)
```

**Comment by zakharfsk** [comment]
@alexandrzhulev Проблема в тому, що багато раз підряд відправляєте на один канал репорт. Потрібно з інтервалом.
Врахую цю проблему в наступних патчах.

**Comment by sobkoNick** [comment]
Хай!
А це норм?
`Your data succsesfull write to settings.json. You can open and see.
Attempt 1 at connecting failed: TimeoutError:
Еnter the code sent to you in the telegram:
Program start...

`
і після цього нічого не виводиться..

**Comment by zakharfsk** [comment]
@sobkoNick Так воно шукає з повідомлення з ключовими словами. Можете протестити
Написати одне з слів в triggers_words.txr  і після нього написати канал який хочете зарепортити і відправтити йе повідомлення в якийсь канал і побачите результат.

Якщо нічого не пише це означає що скріпт не находить текст з трігер словами і вам потрібно просто чекати

**Comment by sobkoNick** [comment]
Ще одне питання - а потрібно, щоб цей телеграм акаунт який я юзаю був підписаний на канали де є інфа які канали репортати чи ні?

**Comment by zakharfsk** [comment]
@sobkoNick не обов'язково, скріпт дивитися по всіх каналах на яких ви є.

І якщо в одному з каналів появиться повідомлення з коючовими словами і силкою або тегом на канал то кинеться репорт

**Comment by lshamanll** [comment]
Де можна взяти наші, нормальні пабліки де постять кого треба забанити? Є в когось список?
Бо в мене поки тільки ця https://t.me/stoprussiachannel

**Comment by zakharfsk** [comment]
@lshamanll Я підписаний на такі:
https://t.me/+4nt7tucfv-05OTky
https://t.me/itarmyofukraine2022
https://t.me/+97Y45he5lOI2ZTky

Сюда часто скиндають силки

**Comment by lshamanll** [comment]
"Your data succsesfull get from settings.json. You can open and see.
Program start..."

і далі мовчить. І не працює. Треба кожен раз заново його ставити?

Також, скільки за раз оброблює посилань? Бо В якийсь момент бот просто встав.

**Comment by zakharfsk** [comment]
@lshamanll Прочитайте вот це [повідомлення](https://github.com/zakharfsk/auto-reporting-fake-channels/issues/3#issuecomment-1055429154). Тут пояснив чому нічого не виводиться. Завтра буде обнова додам що б виводилося все

**Comment by zakharfsk** [comment]
@lshamanll 

> Також, скільки за раз оброблює посилань?

Всі які присутні в поведомленні. Наприклад, є таке повідомлення:
![image](https://user-images.githubusercontent.com/68950796/156411078-1601926b-e09b-4fda-a762-5344ba129b24.png)
З цього повідомлення оброляться всі посилання. Без різниці скільки там буде посилань або лінків всі вони опрацюються.

**Comment by lshamanll** [comment]
> 

так. Я розумію. Просто я перевіряв і кидав повідомлення з тригер словами і лінками, а воно не працює. 
Коли перевстановив, то все знову працювало до якогось моменту. На другий раз вже написав сюди.

Добре чекатимемо на обнову ) Дякую!!

**Comment by dashtabs** [comment]
Привіт!
У мене якщо повідомлення з купою посилань, нічого не виводиться. Якщо закидую собі в канал окремо тріггер слово + одне посилання, то по одному обробляє, але повідомлення виводить два рази. З чим може бути пов'язане? Заздалегідь дякую!
![image_2022-03-02_19-15-06](https://user-images.githubusercontent.com/70433969/156414175-7a6a950a-f609-4257-8cd1-b68cdad148b2.png)

**Comment by sobkoNick** [comment]
@dashtabs цей метод в мене теж працює. Я просто з іншого акаунта форвардю собі повідомлення з каналів і тоді в консолі виводить, що відбувся репорт. Дякую, що написав це!)

**Comment by zakharfsk** [comment]
@dashtabs Попробуйте взяти одне з слів з `triggers_word.txt` і прикріпити всі ті лінки які у вас є і кудась відправити.
Просто ще одна може бути причана того що таго слова або словосполучення не було в `triggers_word.txt`, я веду оптимізацію, щоб воно коректно реагувало, якщо ви хочете запропонувати слова\словосполучення, то можете написати [сюда](https://github.com/zakharfsk/auto-reporting-fake-channels/issues/2).

**Comment by dashtabs** [comment]
@zakharfsk слушне зауваження, дякую. З одним словом чудово працює.

**Comment by dashtabs** [comment]
@zakharfsk ще маю питаннячко: код із Телеграму стабільно вводиться з другої спроби. Підкажіть, будь ласка, з чим це може бути пов'язано?
Але то таке, думаю, не дуже принципово.

**Comment by zakharfsk** [comment]
@dashtabs Можливо десь лишній пробіл і тд. Думаю забрати скриття паролю і коду з ТГ

**Comment by lshamanll** [comment]
це ж не нормлаьно? Вірно?
![E__aws_ddos_auto-reporting-fake-channels-main (1)_](https://user-images.githubusercontent.com/8946605/156626370-b5f6ce74-d21e-4f1e-a392-7c346a725fed.png)

**Comment by zakharfsk** [comment]
@lshamanll Так, якщо багато раз підряд репортите, то появляється кулдаун. Можливо в настпуній обнові поставлю більшу затримку

**Comment by lshamanll** [comment]
> @lshamanll Так, якщо багато раз підряд репортите, то появляється кулдаун. Можливо в настпуній обнові поставлю більшу затримку

Та справа в тому, що я вперше його запустив, вписав неохідні данні, закинув для перевірки пару посилань з тригер словами і зразу це зявилося.

Інколи воно працювало трохи, а потім знову кулдаун(

Можливо хто знає ще подібних ботів по інших соц. мережах?

**Comment by zakharfsk** [comment]
@lshamanll Ну з цим я нічого зробити не можу. Така політика Телеграма
